/* FLASH MESSAGES */
export const ADD_FLASH_MESSAGE = 'ADD_FLASH_MESSAGE';
export const DELETE_FLASH_MESSAGE = 'DELETE_FLASH_MESSAGE';

/* USER */
export const SET_CURRENT_USER = 'SET_CURRENT_USER';

/* DAILY CATEGORIES */
export const ADD_DAILY_CATEGORIES = 'ADD_DAILY_CATEGORIES';
export const INCREMENT_TOTAL_POINTS = 'INCREMENT_TOTAL_POINTS';

/* DAILIES */
export const ADD_DAILIES = 'ADD_DAILIES';
export const REMOVE_DAILY = 'REMOVE_DAILY';
